### ISSUE TITLE
Issues Starting Course

### ISSUE THREAD

**Issue by kieferland** [skills/reusable-workflows#30]
### Summary

When attempting to start the course, the repository doesn't update after waiting 20 seconds and refreshing the page.

### How to reproduce

1. Go to https://github.com/skills/reusable-workflows
2. Right-click on 'Start This Course' and open in new tab
3. Wait 20 seconds and refresh pages
4. See error (page/repo readme.md doesn't update to reflect next steps)

### Additional context

I was able to reproduce this issue on the following [Skills](https://skills.github.com) page activities:
-Secure your repository supply chain
-Secure code game
-Introduction to CodeQL
-Change commit history
-Introduction to secret scanning

https://github.com/skills/reusable-workflows/assets/100397897/3b30024c-15b4-4dc8-b44d-774503c5b08d

**Comment by sinsukehlab** [comment]
All workflows are stopped with an error.
https://github.com/kieferland/skills-reusable-workflows/actions/runs/9472867340
It is likely that the error is a result of this incident (Jun 11, 20:33 - 21:39 UTC), for the commit time is Jun 11, 21:05 UTC.
https://www.githubstatus.com/incidents/lfrlwdg67fn8

**Comment by kieferland** [comment]
Thank you, Shinsuke!  I have book marked the GitHub status website for future reference, cheers.
