### ISSUE TITLE
[Maint] Update actions checkout version in course step

### ISSUE THREAD

**Issue by bharatr21** [skills/reusable-workflows#33]
The documentation still uses an old version of the checkout action `actions/checkout@v3` and can be updated to `actions/checkout@v4`
![GHActions](https://github.com/user-attachments/assets/2b730d59-409b-4f5a-bba1-40520b490c12)

**Comment by nguyenalex836** [comment]
@bharatr21 Thank you for raising this issue and linking your PR! ✨ I have this triaged for the team to review

**Comment by nguyenalex836** [comment]
@bharatr21 Thank you for raising this issue and linking your PR! ✨ I'll triage this for the team to review
